version: "3.9"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - /home/chughes/data/website:/var/www/html
    networks:
      - frontend
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    expose:
      - "9000"
    volumes:
      - /home/chughes/data/website:/var/www/html
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: unless-stopped
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    expose:
      - "3306"
    volumes:
      - home/chughes/data/database:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped
    env_file:
      - .env

volumes:
  mariadb_data:
  wordpress_data:

networks:
  frontend:
  backend:
