version: "3.9"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "443:443"
    networks:
      - frontend
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    ports:
      - "9000:9000"
    volumes: # TODO change mount location
      - wordpressdb-data:/var/
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: always
    # environment:
      # - name=value

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - backend
    restart: always
    # environment:
      # ROOT_PW
      # DB_NAME
      # DB_PW
      # DB_UN

volumes:
  mariadb-data:
  wordpressdb-data:

networks:
  frontend:
  backend:
