version: "3.9"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpressdb-data:/var/www/html
    networks:
      - frontend
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    ports:
      - "9000:9000"
    volumes:
      - wordpressdb-data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: always
    environment:
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - backend
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MARIA_DB_DIR: ${MARIA_DB_DIR}

volumes:
  mariadb-data:
  wordpressdb-data:

networks:
  frontend:
  backend:
