CREATE DATABASE IF NOT EXISTS wordpress_db

ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED by '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON wordpress_db.* TO '$MYSQL_USER'@'%';

FLUSH PRIVILEGES;